In [1]:
import os,sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
books = pd.read_csv("Books.csv")
ratings = pd.read_csv("Ratings.csv")
user = pd.read_csv("Users.csv")

In [3]:
books.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...

In [5]:
ratings.head(1)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0

In [4]:
user.head(1)

   User-ID            Location  Age
0        1  nyc, new york, usa  NaN

In [10]:
print(books.shape)
print(user.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [9]:
print(books.isnull().sum())
print("*********************")
print(user.isnull().sum())
print("*********************")
print(ratings.isnull().sum())
print("*********************")

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64
*********************
User-ID          0
Location         0
Age         110762
dtype: int64
*********************
User-ID        0
ISBN           0
Book-Rating    0
dtype: int64
*********************

In [37]:
print(books.duplicated().sum())
print("*********************")
print(user.duplicated().sum())
print("*********************")
print(ratings.duplicated().sum())
print("*********************")

0
*********************
0
*********************
0
*********************

# Popularity Based Recommendation System

In [12]:
rating_with_name = ratings.merge(books, on='ISBN')
rating_with_name.head(1)

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [20]:
num_rating = rating_with_name.groupby("Book-Title").count()['Book-Rating'].reset_index()
num_rating.rename(columns={'Book-Rating':"Num of Ratings"},inplace=True)
num_rating

                                               Book-Title  Num of Ratings
0        A Light in the Storm: The Civil War Diary of ...               4
1                                   Always Have Popsicles               1
2                    Apple Magic (The Collector's series)               1
3        Ask Lily (Young Women of Faith: Lily Series, ...               1
4        Beyond IBM: Leadership Marketing and Finance ...               1
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.               2
241067                     Ã?Â?rger mit Produkt X. Roman.               4
241068                                Ã?Â?sterlich leben.               1
241069                              Ã?Â?stlich der Berge.               3
241070                                  Ã?Â?thique en toc               2

[241071 rows x 2 columns]

In [23]:
avg_rating = rating_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating.rename(columns={'Book-Rating' : 'Averge Rating'},inplace=True)
avg_rating

                                               Book-Title  Averge Rating
0        A Light in the Storm: The Civil War Diary of ...       2.250000
1                                   Always Have Popsicles       0.000000
2                    Apple Magic (The Collector's series)       0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...       8.000000
4        Beyond IBM: Leadership Marketing and Finance ...       0.000000
...                                                   ...            ...
241066                                      Ã?Â?lpiraten.       0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.       5.250000
241068                                Ã?Â?sterlich leben.       7.000000
241069                              Ã?Â?stlich der Berge.       2.666667
241070                                  Ã?Â?thique en toc       4.000000

[241071 rows x 2 columns]

### Popular Book Table

In [24]:
popular_df = num_rating.merge(avg_rating,on='Book-Title')
popular_df

,Book-Title,Num of Ratings,Averge Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [30]:
popular_df = popular_df[popular_df['Num of Ratings']>=250].sort_values("Averge Rating",ascending=False).head(50)

#Top 50 books which has got good number of rating and average rating is also high.

In [31]:
popular_df

,Book-Title,Num of Ratings,Averge Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [36]:
popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-S']]

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...
63,1984,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,1982,Pocket,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,DIANA GABALDON,1996,Dell,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,Thomas Harris,1991,St. Martin's Press,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,Nick Hornby,1999,Riverhead Books,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,2001,St. Martin's Press,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,William Gerald Golding,1959,Perigee Trade,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...

# Done